config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :listings do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
    resources :orders, only: [:new, :create]
  end

  devise_for :users

  root 'listings#index'

  match '/seller', to: 'listings#seller', via: 'get'
  match '/sales', to: 'orders#sales', via: 'get'
  match '/purchases', to: 'orders#purchases', via: 'get'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100" }, :default_url => "default.jpg"
		validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	else
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg", 
			:storage => :dropbox,
			:dropbox_credentials => Rails.root.join("config/dropbox.yml"), 
			:path => ":style/:id_:filename"
		validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	end

	searchkick
	
	default_scope -> {order('created_at DESC')}
	validates :name, :description, :price, presence: true
	validates :price, numericality: { greater_than: 0 }
	validates :description, presence: true, length: {maximum: 200}
	validates_attachment_presence :image

	belongs_to :user
	has_many :orders
	has_many :reviews, dependent: :destroy
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show]

  def seller
    @listings = Listing.where(user: current_user)
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @reviews = Review.where(listing_id: @listing.id)
      if @reviews.blank?
        @avg_rating = 0
      else
        @avg_rating= @reviews.average(:rating).round(2)
      end
  end

  def search
    if params[:search].present?
      @listings = Listing.search(params[:search])
    else
      @listings = Listing.all
    end
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_user
      unless current_user.admin?
        redirect_to @listing, alert: "You are not authorized"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="center">
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag listing.image.url %>
        <div class="caption">
          <h3><%= link_to listing.name, listing %></h3>
          <p><%= number_to_currency(listing.price) %></p>
          <p><%= "Sold by #{listing.user.name}" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

<br>

<% if user_signed_in? && current_user.admin? %>
<%= link_to "New Listing", new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/search.html.erb
    <% @listings.each do |listing| %>
        <strong><%= link_to listing.name, listing %></strong><br>
        <%= listing.price %><br>
        <p><%= truncate listing.description, length: 80 %></p>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>  |  
          <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
        <% end %>
    <% end %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
            <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.description %></p>

      <p><%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary" %></p>

    <h4>Reviews</h4>

    <%= link_to 'Write Review', new_listing_review_path(@listing), class: "btn btn-primary" %>

    <p class="comment">
    <% if @reviews.blank? %>
      <h3 class="text-center">No reviews yet. Be the first to write one!
        &nbsp;<%= link_to 'Write Review', new_listing_review_path(@listing), class: "btn btn-primary" %></h3>
      <% else %>
    <% @reviews.each do |review| %>
    <h5><%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %></h5>
    <%= time_ago_in_words(review.created_at) %> ago.
    <div class="star-rating" data-score= <%= review.rating %> ></div>
      <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

      <% if user_signed_in? %>
      <% if (review.user == current_user) || (current_user.admin?) %>
      <%= link_to "Edit", edit_listing_review_path(@listing, review) %>  |  
      <%= link_to "Delete", listing_review_path(@listing, review), method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>
      <% end %>

    <% end %>
    <% end %>
  </div>
</div>

<% if user_signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
  <% end %>

  <script>
    $('.star-rating').raty({
      starOff: 'https://dl.dropbox.com/s/a3qo7edr7kljtg9/star-off.png',
      starOn: 'https://dl.dropbox.com/s/aa9cvcklzogag9o/star-on.png',
      starHalf: 'https://dl.dropbox.com/s/wlel79korgp19sz/star-half.png',
      halfShow: true,
      half: true,
      readOnly: true,
      score: function(){
        return $(this).attr('data-score');
      }
    });
  </script>