config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :listings do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
    resources :orders, only: [:new, :create]
  end

  devise_for :users

  root 'listings#index'

  match '/seller', to: 'listings#seller', via: 'get'
  match '/sales', to: 'orders#sales', via: 'get'
  match '/purchases', to: 'orders#purchases', via: 'get'

end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, presence: true
	belongs_to :listing
	belongs_to :seller, class_name: "User"
	belongs_to :buyer, class_name: "User"
	default_scope -> {order('created_at DESC')}

	self.per_page = 10
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales
    @orders = Order.all.where(seller: current_user).paginate(page: params[:page])
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).paginate(page: params[:page])
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: root_url, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@listing, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Complete Order", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<h4><%= @listing.name %></h4>

<p><%= number_to_currency(@listing.price) %></p>

<p><%= image_tag @listing.image.url(:thumb) %></p>

<%= render 'form' %>

<%= link_to 'Back', listing_path(@listing) %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your Purchase History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.seller.first_name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate %>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Your Sales History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.buyer.first_name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate %>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>